### PR TITLE
1471: Update android sdk

### PR DESCRIPTION
**Pull request by f1sh1918**
### Short description

This issue was reported from the play store even i couldn't reproduce any crash.

### Proposed changes

- update android sdk version

### Side effects

- none

### Resolved issues

Fixes: #1471 

### Testing
- build and start the app on android

### CODE REVIEW

**Review by ztefanie — CHANGES_REQUESTED** [review]
...

**Comment by f1sh1918** [comment]
> ...

what does this mean @ztefanie ?

**Comment by ztefanie** [comment]
Yeah sorry, i wrote that the android plugin version must match the dependency version, which I am not sure if this is currently the case. Then i wanted to check, but I am lost in the rabbit hole of getting protoc plugin working again. So not sure it your PR is valid as i can not check. I wanted to edit the message as soon as i get my setup fixed, but it takes forever.

**Review by ztefanie — APPROVED** [review]
I am a little bit confused as i cannot find the dependencies class import and this needs to match the plugin version you updated. Where is our buildscript gradle settings block?

But I could start the app without issues on the emulator so i will approve

**Review by steffenkleinle — APPROVED** [review]
Not sure what exactly to test/look for here but I built nürnberg in the production version and navigated around a bit without anything crashing on my real android device.

**Comment by f1sh1918** [comment]
@ztefanie not sure if this issue is related to this and if this dependency class import is still needed with declarative plugins
https://github.com/digitalfabrik/entitlementcard/pull/1376/files

**Pull request merged**
