### PR TITLE
1653: Add intro slides with stores and disclaimer

### PR DESCRIPTION
**Pull request by ztefanie**
### Short description
Added screenshots with initials stores to intro slides
Added disclaimer text

Fixes: #1653

### CODE REVIEW

**Comment by f1sh1918** [comment]
@ztefanie
did you check if the correct font is used in the screenshots?
You can also create screenshots from my open pr
Even not sure if anyone will notice that

**Comment by ztefanie** [comment]
> @ztefanie did you check if the correct font is used in the screenshots? You can also create screenshots from my open pr Even not sure if anyone will notice that

i think it is good enough for now, we can still update this, especially if more stores are published

**Review by f1sh1918 — APPROVED** [review]

**Comment by f1sh1918** [comment]
@ztefanie 
I think in the finalization ticket is the `applicationUrl` missing
To avoid creating a separate task for adjusting a string could you please provide
` applicationUrl: "https://koblenz.sozialpass.app/erstellen"` in the buildConfig

**Review by steffenkleinle — APPROVED** [review]
LGTM

**Pull request merged**
