### PR TITLE
Upgrade flutter to 3.10

### PR DESCRIPTION
**Pull request by michael-markl**
This was a much more boring upgrade than I thought :D

It needs testing on iOS though.

Here's a changelog: 
https://docs.flutter.dev/release/whats-new#10-may-2023-google-io-2023-310-release

### CODE REVIEW

**Comment by sarahsporck** [comment]
Tested on ios simulator (everything but QRCode)

**Comment by f1sh1918** [comment]
@michael-markl did you test protobuf with this version?
I can not run "build config" and for me it looks like the protoc plugin does only support dart sdk until `>3.0.0`

**Comment by michael-markl** [comment]
> Update: okay had to delete .dart_tool folder

Interesting, I didn't have to do that 🤔  CI seems happy as well... Not sure what the actual issue was for you 😕

**Review by f1sh1918 — APPROVED** [review]
Happened also for sarah. But no matter.

Tested on ios real device. activation works

**Pull request merged**
