### PR TITLE
Project Branch: Whitelabel (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by maxammann**
**DO NOT MERGE UNTIL WHITELABELING IS DONE**

Whitelabeling Epic: https://github.com/digitalfabrik/entitlementcard/issues/444

### CODE REVIEW

**Comment by maxammann** [comment]
**DO NOT MERGE UNTIL WHITELABELING IS DONE**

**Comment by klinzo** [comment]
@maxammann deploy step is failing:
> Uploading:  /tmp/workspace/debs/eak_0.7372-1_all.deb /tmp/workspace/debs/eak-administration_0.7374-1_all.deb /tmp/workspace/debs/eak-backend_0.7376-1_all.deb /tmp/workspace/debs/eak-map-styles_0.4785-1_all.deb /tmp/workspace/debs/eak-martin_0.7375-1_all.deb
Host key verification failed.
Connection closed

**Comment by maxammann** [comment]
Ah yes because the domain change. Fill fix it soon

**Comment by maxammann** [comment]
@michael-markl oke lets close this for now I see now that you are probably getting a lot of notification because you are subscribed to "all activity"

**Pull request closed without merging**
