### PR TITLE
908: Create missing columns in tables

### PR DESCRIPTION
**Pull request by f1sh1918**
- create missing columns in database when new columns were added to the schema

resolves https://github.com/digitalfabrik/entitlementcard/issues/908

### CODE REVIEW

**Comment by f1sh1918** [comment]
Probably i can close this pr since we gonna update our schema with the migrations?!

**Comment by sarahsporck** [comment]
Depends. When we want to rollout the access key, activation code, etc. in the next backend release (before the migration pr has finished) then we may still need this. Depending on how much the production and development db is diverged rn. I'll remove the schema update from the card schema as well in the other branch.

**Comment by michael-markl** [comment]
Weirdly, applications.accessKey, applications.withdrawalDate is already in the prod DB according to the pg_dump.
Which `activation code` do you mean?

As I think, the migration PR should be mergable in the next day(s), I think we can close this (especially as these changes are not *super* urgent, and we would need to do another pg_dump).

**Comment by michael-markl** [comment]
> I thought this changes are not needed at all, since we want to alter the schema via migrations?

Once the migrations PR is merged, this is correct :)

**Comment by f1sh1918** [comment]
not needed after migrations

**Pull request closed without merging**
