### PR TITLE
Fix import of stores

### LINKED ISSUE #1641: Import is failing due to known field in LBE XML
**Describe the bug**
The import fails becaues the LBE added a new field to the XML file.

**To Reproduce**
1. Run the import of LBE data
2. Observe error

**Expected behavior**
The import succeeds

### PR DESCRIPTION
**Pull request by maxammann**
### Short description
Fixes #1641 
### Proposed changes
- Adds a missing field to the Jackson object.
- Disables failing on unknown fields.

### Testing

- Tested locally

### Resolved issues

Fixes: #1641

### CODE REVIEW

**Review by f1sh1918 — APPROVED** [review]
Tested locally
import works as expected

**Review by seluianova — APPROVED** [review]
Tested, worked like a charm

**Comment by f1sh1918** [comment]
@maxammann
You can deploy it on staging and Prod :)

**Comment by maxammann** [comment]
@f1sh1918 should the promotion have happened on main instead of this branch?

**Comment by f1sh1918** [comment]
you can use this branch but it doesn't matter. since there will no artifacts be created but just copied to prod

**Pull request merged**
