### PR TITLE
1039: add mime type text/csv for firefox ubuntu

### PR DESCRIPTION
**Pull request by sarahsporck**

### CODE REVIEW

**Review by michael-markl — APPROVED** [review]
I haven't tested it. Could you reproduce the error?

**Comment by sarahsporck** [comment]
> I haven't tested it. Could you reproduce the error?

Sadly not as I'm currently on a mac. Could you reproduce this? You have set everything up on a ubuntu, right?

**Comment by michael-markl** [comment]
I'm on Kubuntu. However, I could not reproduce it when I tried it once.

**Comment by sarahsporck** [comment]
hmm. okay that's weird. I'll check with daniel whether this could be the issue.

**Review by f1sh1918 — APPROVED** [review]
Tested on firefox. looks fine to me

**Comment by sarahsporck** [comment]
This does not seem to resolve the issue. Therefore I'll close this again

**Pull request closed without merging**
