### PR TITLE
1551: Adjust regionidentifier_unique constraint

### PR DESCRIPTION
**Pull request by seluianova**
### Short description
Adjust regionidentifier_unique constraint to allow regions with the same identifier across different projects

### Proposed changes
- re-create constraint
- add the missing regionIdentifier for sozialpass region nuernberg

### Side effects
- no?

### Resolved issues
Fixes: #1551

### Testing
- migrate DB, run backend
- check regions table: Nürnberg with regionIdentifier 09564 should be represented in both EAK and Nürnberg Pass projects

### CODE REVIEW

**Review by f1sh1918 — CHANGES_REQUESTED** [review]
I think the migration won't work like this.
You have to replace the null value also in the migration, because after installation of a new release package the migration will run and then the service will be restarted.
Your adjustment in the `Setup.kt` will be triggert after migration not before

**Comment by seluianova** [comment]
@f1sh1918 indeed. thanks. updated.

_I added `SET "regionIdentifier" = '00000' WHERE "regionIdentifier" IS NULL` instruction, assuming it's more universal and could be applied to different data sets. however not sure if it can really be useful._

anyway it works for our case as well, during migration we set this dummy value for Nürnberg and then in Setup it is updated to the real one.

**Review by f1sh1918 — APPROVED** [review]
Its fine for me to set it temporarly to `0000`

**Comment by seluianova** [comment]
We probably also need to update:
- stores import for nurnberg (currently we don't set acceptingstores.regionId there)
- add not null constraint for acceptingstores.regionId

**Review by steffenkleinle — APPROVED** [review]
Tested, works like a charm!

**Pull request merged**
