### PR TITLE
Backend test coverage report

### PR DESCRIPTION
**Pull request by seluianova**
### Short description
I suggest applying the **kover** plugin to be able to build test coverage reports in the backend.
It allows you to see the test coverage per line of code like this:
image

### Side effects
This creates a bit of clutter in the circle ci artifacts.
Alternatives to the clutter would be:
- attach all files as an archive, but it would require an additional download/unzip action to view the report
- connect additional tools to upload and view reports there (for example, CMS uses Code Climate: https://codeclimate.com/github/digitalfabrik/integreat-cms/code)
- do not generate a report in ci, use only locally

### Testing
- build the report locally:
`./gradlew koverHtmlReport`
or
- view in circleci:
image

### Resolved issues
n/a

### Additional info
Our current test coverage is 31.4741% (per line)

### CODE REVIEW

**Review by ztefanie — COMMENTED** [review]
Thanks for bringing up this topic and creating a solution.

The tests did not work for me locally, as there where failing tests. I am on current branch and ran the tests with the `./gradlew koverLog koverHtmlReport` command. Are there any additional steps needed before?

```
> Task :test

app.ehrenamtskarte.backend.auth.service.AuthorizerTest > classMethod FAILED
    java.lang.IllegalStateException at DockerClientProviderStrategy.java:277
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

app.ehrenamtskarte.backend.cards.CreateCardFromSelfServiceTest > classMethod FAILED
    java.lang.IllegalStateException at DockerClientProviderStrategy.java:232

app.ehrenamtskarte.backend.userdata.UserImportTest > classMethod FAILED
    java.lang.IllegalStateException at DockerClientProviderStrategy.java:232

45 tests completed, 3 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/steffi/Dokumente/entitlementcard/backend/build/reports/tests/test/index.html
```

some other toughts:
1) we have this codescene integreation ticket, that is releated: https://github.com/digitalfabrik/entitlementcard/issues/1356
2) i do not really mind the cluttering in the artifacts tab, as in the check backend step there are no other artifacts we want to find
3) i would love to get an automatic message to the PR getting information on how many of the changed lines are covered by tests, or how the changes of the PR increased/decreased the test coverage. With only the changes you suggested, i think we will rarely look at this.

**Comment by seluianova** [comment]
> The tests did not work for me locally, as there where failing tests. I am on current branch and ran the tests with the ./gradlew koverLog koverHtmlReport command. Are there any additional steps needed before?

@ztefanie I have an assumption that the tests are not working for you locally on the main branch either. Could you please check? `./gradlew test`
It looks like an issue with the database container.

**Comment by seluianova** [comment]
> With only the changes you suggested, i think we will rarely look at this.

@ztefanie actually I do look into the report when I add tests. maybe then I remove it from CI for now until we implement a nice representation with comments etc using codescene?

**Comment by ztefanie** [comment]
> > With only the changes you suggested, i think we will rarely look at this.
> 
> @ztefanie actually I do look into the report when I add tests. maybe then I remove it from CI for now until we implement a nice representation with an automatic message etc using codescene?

As you already implemented it, I would prefer not to remove it. Maybe an issue with a follow up task of bringing the results of the testing back to github is enough?

**Comment by seluianova** [comment]
I have created a follow-up task https://github.com/digitalfabrik/entitlementcard/issues/1682

**Review by ztefanie — APPROVED** [review]

**Pull request merged**
