### PR TITLE
976: prevent password pasting

### LINKED ISSUE #976: Prevent password pasting for new password
**Is your feature request related to a problem? Please describe.**
Currently by setting a new password the user can copy paste in the input fields.
In the "Neues Password bestätigen" field it should be disabled to force the user typing the password.

**Describe the solution you'd like**
Catch the "paste" event for this field and disable pasting a password

### PR DESCRIPTION
**Pull request by sarahsporck**
fixes #976

### CODE REVIEW

**Comment by steffenkleinle** [comment]
Do we really want that? If you use a password manager with autogenerated and little longer password with special characters this is really annoying :see_no_evil:

**Review by steffenkleinle — APPROVED** [review]

**Comment by michael-markl** [comment]
Personally, I would also be super annoyed by this (and I don't see this very often at all in practice).
Here's also some officially looking blog post that supports my opinion^TM :D 
https://www.ncsc.gov.uk/blog-post/let-them-paste-passwords

We could also ask our security expert @maxammann  :D

**Comment by sarahsporck** [comment]
I don't really have a super strong opinion on this. 
I am also very fine with not doing it, but maybe let's see what @maxammann says.

Small disclaimer. `onPaste={e => e.preventDefault()}` does not stop the user from drag'n'dropping a text into the field. Further it seems that especially managers that already run in the browser set the text on the dom element directly, as the firefox password manager still works.

**Comment by maxammann** [comment]
I'm usually very annoyed if a website forces me to retype a password :D

I think if a user knows copy paste that well, then it is fine to do that.

**Comment by maxammann** [comment]
Apart from that the solution is sufficient I think.

**Pull request closed without merging**
