### PR TITLE
552: Upgrade Flutter and dependencies

### LINKED ISSUE #552: Upgrade Flutter and dependencies
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Update Flutter to version 3.3.0

**Additional context**
Let's get the latest performance and security fixes from Flutter.

### PR DESCRIPTION
**Pull request by michael-markl**
Fixes #552 .

### CODE REVIEW

**Review by maxammann — APPROVED** [review]
Compilation works, starts, but crashes. This is not related to this PR though I think. The maplibre renderer just crashes when used on an M1.

I have not found a workaround yet. But it works on a real device.

I would say we merge this and look for a workaround in the future.

**Comment by michael-markl** [comment]
Nice, how did you test it on a real device? Do you have an iPhone for testing?

**Comment by maxammann** [comment]
I have a very very old iphone 5.

**Comment by michael-markl** [comment]
Is it an actual iphone 5? What's the iOS version?

**Comment by maxammann** [comment]
5s with 12.5.5

**Pull request merged**
