### PR TITLE
1543: Fix missing metadata promotion

### PR DESCRIPTION
**Pull request by f1sh1918**
### Short description

The release notes couldn't be uploaded during promoting for ios.

### Proposed changes

- adjust the `metadata_path`

### Side effects

- none

### Resolved issues

Fixes: #1543

### CODE REVIEW

**Comment by steffenkleinle** [comment]
@f1sh1918 did you test whether this actually fixes the issue?

**Comment by f1sh1918** [comment]
@steffenkleinle difficult since i would have to do a promotion, no?

**Comment by steffenkleinle** [comment]
> @steffenkleinle difficult since i would have to do a promotion, no?

Then I'd rather use the path I suggested as we know that it works in Integreat, right?

**Review by steffenkleinle — APPROVED** [review]

**Review by seluianova — APPROVED** [review]

**Review by ztefanie — APPROVED** [review]

**Comment by ztefanie** [comment]
> @steffenkleinle difficult since i would have to do a promotion, no?

You can set the skip_app_version_update to true and then test if it works:

**Comment by f1sh1918** [comment]
> > @steffenkleinle difficult since i would have to do a promotion, no?
> 
> You can set the skip_app_version_update to true and then test if it works:

@ztefanie i didn't really get this from documentation. Do i have to create a new version for testflight (beta release also) or can i somehow test the promotion with the old bundle?

**Comment by ztefanie** [comment]
you only changed the metadata upload for the promotion, so yes you would need to promote a beta to test it. 

But I think it really makes sense to also add your adjustments also to the appstoreconnect upload.

**Comment by f1sh1918** [comment]
> you only changed the metadata upload for the promotion, so yes you would need to promote a beta to test it.
> 
> But I think it really makes sense to also add your adjustments also to the appstoreconnect upload.

Alright gonna check next week. PLEASE DO NOT MERGE THIS :)

**Comment by f1sh1918** [comment]
hm i created a testflight build and uploaded it.
Now i tried to promote it with the settings you suggested @ztefanie 
But it can't find the appStoreVersion.
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/6533/workflows/67de5af7-4248-4682-8cfa-629bbad88477/jobs/45764
Can you find any issues in the fastlane config?
To ensure that it will not submitted for review is also set this to false temporary.
The build number and app version seem to be correct.
Here is the issued ci workflow
https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/6533/workflows/67de5af7-4248-4682-8cfa-629bbad88477/jobs/45764

**Comment by ztefanie** [comment]
Sorry about the confusion.I think this is expected behavior as skip_app_version_update blocks updating this version and therefore cannot find a version for promoting and leading to this error. 
As we currently have no apps in review processes it is fine, if you remove the skip_app_version_update property (sets it to default , which is false) and just use the "submit_for_review" false.

**Comment by f1sh1918** [comment]
> Sorry about the confusion.I think this is expected behavior as skip_app_version_update blocks updating this version and therefore cannot find a version for promoting and leading to this error. As we currently have no apps in review processes it is fine, if you remove the skip_app_version_update property (sets it to default , which is false) and just use the "submit_for_review" false.
> 
> Edit: Wouldn't it make more sense to already add the metadata to the beta?

You mean for the `upload_to_testflight` @ztefanie ?
I added this but it seems like its not possible for this function, since i was facing an error

**Pull request merged**
